/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { ORDERBOOK_PROGRAM_ADDRESS } from "../programs";

export const CANCEL_ORDER_BY_CLIENT_ID_DISCRIMINATOR = 8;

export function getCancelOrderByClientIdDiscriminatorBytes() {
  return getU8Encoder().encode(CANCEL_ORDER_BY_CLIENT_ID_DISCRIMINATOR);
}

export type CancelOrderByClientIdInstruction<
  TProgram extends string = typeof ORDERBOOK_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountOpenOrdersAccount extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountBids extends string | AccountMeta<string> = string,
  TAccountAsks extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountOpenOrdersAccount extends string
        ? WritableAccount<TAccountOpenOrdersAccount>
        : TAccountOpenOrdersAccount,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountBids extends string
        ? WritableAccount<TAccountBids>
        : TAccountBids,
      TAccountAsks extends string
        ? WritableAccount<TAccountAsks>
        : TAccountAsks,
      ...TRemainingAccounts,
    ]
  >;

export type CancelOrderByClientIdInstructionData = {
  discriminator: number;
  clientId: bigint;
};

export type CancelOrderByClientIdInstructionDataArgs = {
  clientId: number | bigint;
};

export function getCancelOrderByClientIdInstructionDataEncoder(): FixedSizeEncoder<CancelOrderByClientIdInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["clientId", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: CANCEL_ORDER_BY_CLIENT_ID_DISCRIMINATOR,
    }),
  );
}

export function getCancelOrderByClientIdInstructionDataDecoder(): FixedSizeDecoder<CancelOrderByClientIdInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["clientId", getU64Decoder()],
  ]);
}

export function getCancelOrderByClientIdInstructionDataCodec(): FixedSizeCodec<
  CancelOrderByClientIdInstructionDataArgs,
  CancelOrderByClientIdInstructionData
> {
  return combineCodec(
    getCancelOrderByClientIdInstructionDataEncoder(),
    getCancelOrderByClientIdInstructionDataDecoder(),
  );
}

export type CancelOrderByClientIdInput<
  TAccountSigner extends string = string,
  TAccountOpenOrdersAccount extends string = string,
  TAccountMarket extends string = string,
  TAccountBids extends string = string,
  TAccountAsks extends string = string,
> = {
  /** Order owner */
  signer: TransactionSigner<TAccountSigner>;
  /** OO account */
  openOrdersAccount: Address<TAccountOpenOrdersAccount>;
  /** Market state */
  market: Address<TAccountMarket>;
  /** Bids BookSide */
  bids: Address<TAccountBids>;
  /** Asks BookSide */
  asks: Address<TAccountAsks>;
  clientId: CancelOrderByClientIdInstructionDataArgs["clientId"];
};

export function getCancelOrderByClientIdInstruction<
  TAccountSigner extends string,
  TAccountOpenOrdersAccount extends string,
  TAccountMarket extends string,
  TAccountBids extends string,
  TAccountAsks extends string,
  TProgramAddress extends Address = typeof ORDERBOOK_PROGRAM_ADDRESS,
>(
  input: CancelOrderByClientIdInput<
    TAccountSigner,
    TAccountOpenOrdersAccount,
    TAccountMarket,
    TAccountBids,
    TAccountAsks
  >,
  config?: { programAddress?: TProgramAddress },
): CancelOrderByClientIdInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountOpenOrdersAccount,
  TAccountMarket,
  TAccountBids,
  TAccountAsks
> {
  // Program address.
  const programAddress = config?.programAddress ?? ORDERBOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: false },
    openOrdersAccount: {
      value: input.openOrdersAccount ?? null,
      isWritable: true,
    },
    market: { value: input.market ?? null, isWritable: false },
    bids: { value: input.bids ?? null, isWritable: true },
    asks: { value: input.asks ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("openOrdersAccount", accounts.openOrdersAccount),
      getAccountMeta("market", accounts.market),
      getAccountMeta("bids", accounts.bids),
      getAccountMeta("asks", accounts.asks),
    ],
    data: getCancelOrderByClientIdInstructionDataEncoder().encode(
      args as CancelOrderByClientIdInstructionDataArgs,
    ),
    programAddress,
  } as CancelOrderByClientIdInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountOpenOrdersAccount,
    TAccountMarket,
    TAccountBids,
    TAccountAsks
  >);
}

export type ParsedCancelOrderByClientIdInstruction<
  TProgram extends string = typeof ORDERBOOK_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Order owner */
    signer: TAccountMetas[0];
    /** OO account */
    openOrdersAccount: TAccountMetas[1];
    /** Market state */
    market: TAccountMetas[2];
    /** Bids BookSide */
    bids: TAccountMetas[3];
    /** Asks BookSide */
    asks: TAccountMetas[4];
  };
  data: CancelOrderByClientIdInstructionData;
};

export function parseCancelOrderByClientIdInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCancelOrderByClientIdInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      openOrdersAccount: getNextAccount(),
      market: getNextAccount(),
      bids: getNextAccount(),
      asks: getNextAccount(),
    },
    data: getCancelOrderByClientIdInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
