/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { ORDERBOOK_PROGRAM_ADDRESS } from "../programs";

export const CREATE_ORDERBOOK_MARKET_DISCRIMINATOR = 0;

export function getCreateOrderbookMarketDiscriminatorBytes() {
  return getU8Encoder().encode(CREATE_ORDERBOOK_MARKET_DISCRIMINATOR);
}

export type CreateOrderbookMarketInstruction<
  TProgram extends string = typeof ORDERBOOK_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountBids extends string | AccountMeta<string> = string,
  TAccountAsks extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountBids extends string
        ? WritableAccount<TAccountBids>
        : TAccountBids,
      TAccountAsks extends string
        ? WritableAccount<TAccountAsks>
        : TAccountAsks,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateOrderbookMarketInstructionData = {
  discriminator: number;
  baseLotSize: bigint;
  quoteLotSize: bigint;
  timeExpiry: bigint;
  marketIndex: number;
  bump: number;
  bidsBump: number;
  asksBump: number;
  padding: ReadonlyUint8Array;
  name: ReadonlyUint8Array;
  admin: ReadonlyUint8Array;
};

export type CreateOrderbookMarketInstructionDataArgs = {
  baseLotSize: number | bigint;
  quoteLotSize: number | bigint;
  timeExpiry: number | bigint;
  marketIndex: number;
  bump: number;
  bidsBump: number;
  asksBump: number;
  padding: ReadonlyUint8Array;
  name: ReadonlyUint8Array;
  admin: ReadonlyUint8Array;
};

export function getCreateOrderbookMarketInstructionDataEncoder(): FixedSizeEncoder<CreateOrderbookMarketInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["baseLotSize", getI64Encoder()],
      ["quoteLotSize", getI64Encoder()],
      ["timeExpiry", getI64Encoder()],
      ["marketIndex", getU16Encoder()],
      ["bump", getU8Encoder()],
      ["bidsBump", getU8Encoder()],
      ["asksBump", getU8Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 3)],
      ["name", fixEncoderSize(getBytesEncoder(), 16)],
      ["admin", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({
      ...value,
      discriminator: CREATE_ORDERBOOK_MARKET_DISCRIMINATOR,
    }),
  );
}

export function getCreateOrderbookMarketInstructionDataDecoder(): FixedSizeDecoder<CreateOrderbookMarketInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["baseLotSize", getI64Decoder()],
    ["quoteLotSize", getI64Decoder()],
    ["timeExpiry", getI64Decoder()],
    ["marketIndex", getU16Decoder()],
    ["bump", getU8Decoder()],
    ["bidsBump", getU8Decoder()],
    ["asksBump", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 3)],
    ["name", fixDecoderSize(getBytesDecoder(), 16)],
    ["admin", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getCreateOrderbookMarketInstructionDataCodec(): FixedSizeCodec<
  CreateOrderbookMarketInstructionDataArgs,
  CreateOrderbookMarketInstructionData
> {
  return combineCodec(
    getCreateOrderbookMarketInstructionDataEncoder(),
    getCreateOrderbookMarketInstructionDataDecoder(),
  );
}

export type CreateOrderbookMarketInput<
  TAccountPayer extends string = string,
  TAccountMarket extends string = string,
  TAccountBids extends string = string,
  TAccountAsks extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Fee payer */
  payer: TransactionSigner<TAccountPayer>;
  /** Market state PDA */
  market: Address<TAccountMarket>;
  /** Bids BookSide PDA */
  bids: Address<TAccountBids>;
  /** Asks BookSide PDA */
  asks: Address<TAccountAsks>;
  /** System program */
  systemProgram?: Address<TAccountSystemProgram>;
  baseLotSize: CreateOrderbookMarketInstructionDataArgs["baseLotSize"];
  quoteLotSize: CreateOrderbookMarketInstructionDataArgs["quoteLotSize"];
  timeExpiry: CreateOrderbookMarketInstructionDataArgs["timeExpiry"];
  marketIndex: CreateOrderbookMarketInstructionDataArgs["marketIndex"];
  bump: CreateOrderbookMarketInstructionDataArgs["bump"];
  bidsBump: CreateOrderbookMarketInstructionDataArgs["bidsBump"];
  asksBump: CreateOrderbookMarketInstructionDataArgs["asksBump"];
  padding: CreateOrderbookMarketInstructionDataArgs["padding"];
  name: CreateOrderbookMarketInstructionDataArgs["name"];
  admin: CreateOrderbookMarketInstructionDataArgs["admin"];
};

export function getCreateOrderbookMarketInstruction<
  TAccountPayer extends string,
  TAccountMarket extends string,
  TAccountBids extends string,
  TAccountAsks extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ORDERBOOK_PROGRAM_ADDRESS,
>(
  input: CreateOrderbookMarketInput<
    TAccountPayer,
    TAccountMarket,
    TAccountBids,
    TAccountAsks,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateOrderbookMarketInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountMarket,
  TAccountBids,
  TAccountAsks,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ORDERBOOK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    bids: { value: input.bids ?? null, isWritable: true },
    asks: { value: input.asks ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("market", accounts.market),
      getAccountMeta("bids", accounts.bids),
      getAccountMeta("asks", accounts.asks),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getCreateOrderbookMarketInstructionDataEncoder().encode(
      args as CreateOrderbookMarketInstructionDataArgs,
    ),
    programAddress,
  } as CreateOrderbookMarketInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountMarket,
    TAccountBids,
    TAccountAsks,
    TAccountSystemProgram
  >);
}

export type ParsedCreateOrderbookMarketInstruction<
  TProgram extends string = typeof ORDERBOOK_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Fee payer */
    payer: TAccountMetas[0];
    /** Market state PDA */
    market: TAccountMetas[1];
    /** Bids BookSide PDA */
    bids: TAccountMetas[2];
    /** Asks BookSide PDA */
    asks: TAccountMetas[3];
    /** System program */
    systemProgram: TAccountMetas[4];
  };
  data: CreateOrderbookMarketInstructionData;
};

export function parseCreateOrderbookMarketInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateOrderbookMarketInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      market: getNextAccount(),
      bids: getNextAccount(),
      asks: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateOrderbookMarketInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
