/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { TRIGGER_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const EDIT_TRIGGER_DISCRIMINATOR = 1;

export function getEditTriggerDiscriminatorBytes() {
  return getU8Encoder().encode(EDIT_TRIGGER_DISCRIMINATOR);
}

export type EditTriggerInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountTriggerOrder extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTriggerOrder extends string
        ? WritableAccount<TAccountTriggerOrder>
        : TAccountTriggerOrder,
      ...TRemainingAccounts,
    ]
  >;

export type EditTriggerInstructionData = {
  discriminator: number;
  newTriggerPrice: bigint;
  newSizeLots: bigint;
  newExpiry: bigint;
  padding: ReadonlyUint8Array;
};

export type EditTriggerInstructionDataArgs = {
  newTriggerPrice: number | bigint;
  newSizeLots: number | bigint;
  newExpiry: number | bigint;
  padding: ReadonlyUint8Array;
};

export function getEditTriggerInstructionDataEncoder(): FixedSizeEncoder<EditTriggerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["newTriggerPrice", getI64Encoder()],
      ["newSizeLots", getI64Encoder()],
      ["newExpiry", getI64Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 8)],
    ]),
    (value) => ({ ...value, discriminator: EDIT_TRIGGER_DISCRIMINATOR }),
  );
}

export function getEditTriggerInstructionDataDecoder(): FixedSizeDecoder<EditTriggerInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["newTriggerPrice", getI64Decoder()],
    ["newSizeLots", getI64Decoder()],
    ["newExpiry", getI64Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getEditTriggerInstructionDataCodec(): FixedSizeCodec<
  EditTriggerInstructionDataArgs,
  EditTriggerInstructionData
> {
  return combineCodec(
    getEditTriggerInstructionDataEncoder(),
    getEditTriggerInstructionDataDecoder(),
  );
}

export type EditTriggerInput<
  TAccountSigner extends string = string,
  TAccountTriggerOrder extends string = string,
> = {
  /** Fee payer */
  signer: TransactionSigner<TAccountSigner>;
  /** Trigger order PDA */
  triggerOrder: Address<TAccountTriggerOrder>;
  newTriggerPrice: EditTriggerInstructionDataArgs["newTriggerPrice"];
  newSizeLots: EditTriggerInstructionDataArgs["newSizeLots"];
  newExpiry: EditTriggerInstructionDataArgs["newExpiry"];
  padding: EditTriggerInstructionDataArgs["padding"];
};

export function getEditTriggerInstruction<
  TAccountSigner extends string,
  TAccountTriggerOrder extends string,
  TProgramAddress extends Address = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
>(
  input: EditTriggerInput<TAccountSigner, TAccountTriggerOrder>,
  config?: { programAddress?: TProgramAddress },
): EditTriggerInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountTriggerOrder
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRIGGER_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("triggerOrder", accounts.triggerOrder),
    ],
    data: getEditTriggerInstructionDataEncoder().encode(
      args as EditTriggerInstructionDataArgs,
    ),
    programAddress,
  } as EditTriggerInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTriggerOrder
  >);
}

export type ParsedEditTriggerInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Fee payer */
    signer: TAccountMetas[0];
    /** Trigger order PDA */
    triggerOrder: TAccountMetas[1];
  };
  data: EditTriggerInstructionData;
};

export function parseEditTriggerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedEditTriggerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { signer: getNextAccount(), triggerOrder: getNextAccount() },
    data: getEditTriggerInstructionDataDecoder().decode(instruction.data),
  };
}
