/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { TRIGGER_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const EXECUTE_TRIGGER_DISCRIMINATOR = 2;

export function getExecuteTriggerDiscriminatorBytes() {
  return getU8Encoder().encode(EXECUTE_TRIGGER_DISCRIMINATOR);
}

export type ExecuteTriggerInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountKeeper extends string | AccountMeta<string> = string,
  TAccountTriggerAuthority extends string | AccountMeta<string> = string,
  TAccountTriggerOrderOwner extends string | AccountMeta<string> = string,
  TAccountTriggerOrder extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountOpenOrdersAccount extends string | AccountMeta<string> = string,
  TAccountBids extends string | AccountMeta<string> = string,
  TAccountAsks extends string | AccountMeta<string> = string,
  TAccountFillsLog extends string | AccountMeta<string> = string,
  TAccountOracle extends string | AccountMeta<string> = string,
  TAccountOrderbookProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountKeeper extends string
        ? WritableSignerAccount<TAccountKeeper> &
            AccountSignerMeta<TAccountKeeper>
        : TAccountKeeper,
      TAccountTriggerAuthority extends string
        ? WritableAccount<TAccountTriggerAuthority>
        : TAccountTriggerAuthority,
      TAccountTriggerOrderOwner extends string
        ? WritableAccount<TAccountTriggerOrderOwner>
        : TAccountTriggerOrderOwner,
      TAccountTriggerOrder extends string
        ? WritableAccount<TAccountTriggerOrder>
        : TAccountTriggerOrder,
      TAccountMarket extends string
        ? WritableAccount<TAccountMarket>
        : TAccountMarket,
      TAccountOpenOrdersAccount extends string
        ? WritableAccount<TAccountOpenOrdersAccount>
        : TAccountOpenOrdersAccount,
      TAccountBids extends string
        ? WritableAccount<TAccountBids>
        : TAccountBids,
      TAccountAsks extends string
        ? WritableAccount<TAccountAsks>
        : TAccountAsks,
      TAccountFillsLog extends string
        ? WritableAccount<TAccountFillsLog>
        : TAccountFillsLog,
      TAccountOracle extends string
        ? ReadonlyAccount<TAccountOracle>
        : TAccountOracle,
      TAccountOrderbookProgram extends string
        ? ReadonlyAccount<TAccountOrderbookProgram>
        : TAccountOrderbookProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ExecuteTriggerInstructionData = {
  discriminator: number;
  marketIndex: number;
  bumpFillsLog: number;
  bumpAuthority: number;
  padding: ReadonlyUint8Array;
};

export type ExecuteTriggerInstructionDataArgs = {
  marketIndex: number;
  bumpFillsLog: number;
  bumpAuthority: number;
  padding: ReadonlyUint8Array;
};

export function getExecuteTriggerInstructionDataEncoder(): FixedSizeEncoder<ExecuteTriggerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["marketIndex", getU16Encoder()],
      ["bumpFillsLog", getU8Encoder()],
      ["bumpAuthority", getU8Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 4)],
    ]),
    (value) => ({ ...value, discriminator: EXECUTE_TRIGGER_DISCRIMINATOR }),
  );
}

export function getExecuteTriggerInstructionDataDecoder(): FixedSizeDecoder<ExecuteTriggerInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["marketIndex", getU16Decoder()],
    ["bumpFillsLog", getU8Decoder()],
    ["bumpAuthority", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 4)],
  ]);
}

export function getExecuteTriggerInstructionDataCodec(): FixedSizeCodec<
  ExecuteTriggerInstructionDataArgs,
  ExecuteTriggerInstructionData
> {
  return combineCodec(
    getExecuteTriggerInstructionDataEncoder(),
    getExecuteTriggerInstructionDataDecoder(),
  );
}

export type ExecuteTriggerInput<
  TAccountKeeper extends string = string,
  TAccountTriggerAuthority extends string = string,
  TAccountTriggerOrderOwner extends string = string,
  TAccountTriggerOrder extends string = string,
  TAccountMarket extends string = string,
  TAccountOpenOrdersAccount extends string = string,
  TAccountBids extends string = string,
  TAccountAsks extends string = string,
  TAccountFillsLog extends string = string,
  TAccountOracle extends string = string,
  TAccountOrderbookProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Fee payer */
  keeper: TransactionSigner<TAccountKeeper>;
  /** Trigger order authority PDA */
  triggerAuthority: Address<TAccountTriggerAuthority>;
  /** Trigger order owner PDA */
  triggerOrderOwner: Address<TAccountTriggerOrderOwner>;
  /** Trigger order PDA */
  triggerOrder: Address<TAccountTriggerOrder>;
  /** Market PDA */
  market: Address<TAccountMarket>;
  /** Open orders account PDA */
  openOrdersAccount: Address<TAccountOpenOrdersAccount>;
  /** Bids PDA */
  bids: Address<TAccountBids>;
  /** Asks PDA */
  asks: Address<TAccountAsks>;
  /** Fills log PDA */
  fillsLog: Address<TAccountFillsLog>;
  /** Switchboard SOL/USD feed */
  oracle: Address<TAccountOracle>;
  /** Orderbook Program */
  orderbookProgram: Address<TAccountOrderbookProgram>;
  /** System program */
  systemProgram?: Address<TAccountSystemProgram>;
  marketIndex: ExecuteTriggerInstructionDataArgs["marketIndex"];
  bumpFillsLog: ExecuteTriggerInstructionDataArgs["bumpFillsLog"];
  bumpAuthority: ExecuteTriggerInstructionDataArgs["bumpAuthority"];
  padding: ExecuteTriggerInstructionDataArgs["padding"];
};

export function getExecuteTriggerInstruction<
  TAccountKeeper extends string,
  TAccountTriggerAuthority extends string,
  TAccountTriggerOrderOwner extends string,
  TAccountTriggerOrder extends string,
  TAccountMarket extends string,
  TAccountOpenOrdersAccount extends string,
  TAccountBids extends string,
  TAccountAsks extends string,
  TAccountFillsLog extends string,
  TAccountOracle extends string,
  TAccountOrderbookProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
>(
  input: ExecuteTriggerInput<
    TAccountKeeper,
    TAccountTriggerAuthority,
    TAccountTriggerOrderOwner,
    TAccountTriggerOrder,
    TAccountMarket,
    TAccountOpenOrdersAccount,
    TAccountBids,
    TAccountAsks,
    TAccountFillsLog,
    TAccountOracle,
    TAccountOrderbookProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ExecuteTriggerInstruction<
  TProgramAddress,
  TAccountKeeper,
  TAccountTriggerAuthority,
  TAccountTriggerOrderOwner,
  TAccountTriggerOrder,
  TAccountMarket,
  TAccountOpenOrdersAccount,
  TAccountBids,
  TAccountAsks,
  TAccountFillsLog,
  TAccountOracle,
  TAccountOrderbookProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRIGGER_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    keeper: { value: input.keeper ?? null, isWritable: true },
    triggerAuthority: {
      value: input.triggerAuthority ?? null,
      isWritable: true,
    },
    triggerOrderOwner: {
      value: input.triggerOrderOwner ?? null,
      isWritable: true,
    },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: true },
    openOrdersAccount: {
      value: input.openOrdersAccount ?? null,
      isWritable: true,
    },
    bids: { value: input.bids ?? null, isWritable: true },
    asks: { value: input.asks ?? null, isWritable: true },
    fillsLog: { value: input.fillsLog ?? null, isWritable: true },
    oracle: { value: input.oracle ?? null, isWritable: false },
    orderbookProgram: {
      value: input.orderbookProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("keeper", accounts.keeper),
      getAccountMeta("triggerAuthority", accounts.triggerAuthority),
      getAccountMeta("triggerOrderOwner", accounts.triggerOrderOwner),
      getAccountMeta("triggerOrder", accounts.triggerOrder),
      getAccountMeta("market", accounts.market),
      getAccountMeta("openOrdersAccount", accounts.openOrdersAccount),
      getAccountMeta("bids", accounts.bids),
      getAccountMeta("asks", accounts.asks),
      getAccountMeta("fillsLog", accounts.fillsLog),
      getAccountMeta("oracle", accounts.oracle),
      getAccountMeta("orderbookProgram", accounts.orderbookProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getExecuteTriggerInstructionDataEncoder().encode(
      args as ExecuteTriggerInstructionDataArgs,
    ),
    programAddress,
  } as ExecuteTriggerInstruction<
    TProgramAddress,
    TAccountKeeper,
    TAccountTriggerAuthority,
    TAccountTriggerOrderOwner,
    TAccountTriggerOrder,
    TAccountMarket,
    TAccountOpenOrdersAccount,
    TAccountBids,
    TAccountAsks,
    TAccountFillsLog,
    TAccountOracle,
    TAccountOrderbookProgram,
    TAccountSystemProgram
  >);
}

export type ParsedExecuteTriggerInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Fee payer */
    keeper: TAccountMetas[0];
    /** Trigger order authority PDA */
    triggerAuthority: TAccountMetas[1];
    /** Trigger order owner PDA */
    triggerOrderOwner: TAccountMetas[2];
    /** Trigger order PDA */
    triggerOrder: TAccountMetas[3];
    /** Market PDA */
    market: TAccountMetas[4];
    /** Open orders account PDA */
    openOrdersAccount: TAccountMetas[5];
    /** Bids PDA */
    bids: TAccountMetas[6];
    /** Asks PDA */
    asks: TAccountMetas[7];
    /** Fills log PDA */
    fillsLog: TAccountMetas[8];
    /** Switchboard SOL/USD feed */
    oracle: TAccountMetas[9];
    /** Orderbook Program */
    orderbookProgram: TAccountMetas[10];
    /** System program */
    systemProgram: TAccountMetas[11];
  };
  data: ExecuteTriggerInstructionData;
};

export function parseExecuteTriggerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedExecuteTriggerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 12,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      keeper: getNextAccount(),
      triggerAuthority: getNextAccount(),
      triggerOrderOwner: getNextAccount(),
      triggerOrder: getNextAccount(),
      market: getNextAccount(),
      openOrdersAccount: getNextAccount(),
      bids: getNextAccount(),
      asks: getNextAccount(),
      fillsLog: getNextAccount(),
      oracle: getNextAccount(),
      orderbookProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getExecuteTriggerInstructionDataDecoder().decode(instruction.data),
  };
}
