/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { TRIGGER_PROGRAM_PROGRAM_ADDRESS } from "../programs";
import {
  getPlaceTriggerOrderParamsDecoder,
  getPlaceTriggerOrderParamsEncoder,
  type PlaceTriggerOrderParams,
  type PlaceTriggerOrderParamsArgs,
} from "../types";

export const PLACE_TRIGGER_ORDER_DISCRIMINATOR = 0;

export function getPlaceTriggerOrderDiscriminatorBytes() {
  return getU8Encoder().encode(PLACE_TRIGGER_ORDER_DISCRIMINATOR);
}

export type PlaceTriggerOrderInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountTriggerOrder extends string | AccountMeta<string> = string,
  TAccountOpenOrdersAccount extends string | AccountMeta<string> = string,
  TAccountTriggerAuthority extends string | AccountMeta<string> = string,
  TAccountFillsLog extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountOrderbookProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTriggerOrder extends string
        ? WritableAccount<TAccountTriggerOrder>
        : TAccountTriggerOrder,
      TAccountOpenOrdersAccount extends string
        ? WritableAccount<TAccountOpenOrdersAccount>
        : TAccountOpenOrdersAccount,
      TAccountTriggerAuthority extends string
        ? ReadonlyAccount<TAccountTriggerAuthority>
        : TAccountTriggerAuthority,
      TAccountFillsLog extends string
        ? WritableAccount<TAccountFillsLog>
        : TAccountFillsLog,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountOrderbookProgram extends string
        ? ReadonlyAccount<TAccountOrderbookProgram>
        : TAccountOrderbookProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PlaceTriggerOrderInstructionData = {
  discriminator: number;
  placeTriggerOrderParams: PlaceTriggerOrderParams;
};

export type PlaceTriggerOrderInstructionDataArgs = {
  placeTriggerOrderParams: PlaceTriggerOrderParamsArgs;
};

export function getPlaceTriggerOrderInstructionDataEncoder(): Encoder<PlaceTriggerOrderInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["placeTriggerOrderParams", getPlaceTriggerOrderParamsEncoder()],
    ]),
    (value) => ({ ...value, discriminator: PLACE_TRIGGER_ORDER_DISCRIMINATOR }),
  );
}

export function getPlaceTriggerOrderInstructionDataDecoder(): Decoder<PlaceTriggerOrderInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["placeTriggerOrderParams", getPlaceTriggerOrderParamsDecoder()],
  ]);
}

export function getPlaceTriggerOrderInstructionDataCodec(): Codec<
  PlaceTriggerOrderInstructionDataArgs,
  PlaceTriggerOrderInstructionData
> {
  return combineCodec(
    getPlaceTriggerOrderInstructionDataEncoder(),
    getPlaceTriggerOrderInstructionDataDecoder(),
  );
}

export type PlaceTriggerOrderInput<
  TAccountSigner extends string = string,
  TAccountTriggerOrder extends string = string,
  TAccountOpenOrdersAccount extends string = string,
  TAccountTriggerAuthority extends string = string,
  TAccountFillsLog extends string = string,
  TAccountMarket extends string = string,
  TAccountOrderbookProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Fee payer */
  signer: TransactionSigner<TAccountSigner>;
  /** Trigger order PDA */
  triggerOrder: Address<TAccountTriggerOrder>;
  /** Open orders account PDA */
  openOrdersAccount: Address<TAccountOpenOrdersAccount>;
  /** Trigger authority PDA */
  triggerAuthority: Address<TAccountTriggerAuthority>;
  /** FillsLog PDA */
  fillsLog: Address<TAccountFillsLog>;
  /** Market state PDA */
  market: Address<TAccountMarket>;
  /** Orderbook program */
  orderbookProgram: Address<TAccountOrderbookProgram>;
  /** System program */
  systemProgram?: Address<TAccountSystemProgram>;
  placeTriggerOrderParams: PlaceTriggerOrderInstructionDataArgs["placeTriggerOrderParams"];
};

export function getPlaceTriggerOrderInstruction<
  TAccountSigner extends string,
  TAccountTriggerOrder extends string,
  TAccountOpenOrdersAccount extends string,
  TAccountTriggerAuthority extends string,
  TAccountFillsLog extends string,
  TAccountMarket extends string,
  TAccountOrderbookProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
>(
  input: PlaceTriggerOrderInput<
    TAccountSigner,
    TAccountTriggerOrder,
    TAccountOpenOrdersAccount,
    TAccountTriggerAuthority,
    TAccountFillsLog,
    TAccountMarket,
    TAccountOrderbookProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): PlaceTriggerOrderInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountTriggerOrder,
  TAccountOpenOrdersAccount,
  TAccountTriggerAuthority,
  TAccountFillsLog,
  TAccountMarket,
  TAccountOrderbookProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRIGGER_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
    openOrdersAccount: {
      value: input.openOrdersAccount ?? null,
      isWritable: true,
    },
    triggerAuthority: {
      value: input.triggerAuthority ?? null,
      isWritable: false,
    },
    fillsLog: { value: input.fillsLog ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    orderbookProgram: {
      value: input.orderbookProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("triggerOrder", accounts.triggerOrder),
      getAccountMeta("openOrdersAccount", accounts.openOrdersAccount),
      getAccountMeta("triggerAuthority", accounts.triggerAuthority),
      getAccountMeta("fillsLog", accounts.fillsLog),
      getAccountMeta("market", accounts.market),
      getAccountMeta("orderbookProgram", accounts.orderbookProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getPlaceTriggerOrderInstructionDataEncoder().encode(
      args as PlaceTriggerOrderInstructionDataArgs,
    ),
    programAddress,
  } as PlaceTriggerOrderInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTriggerOrder,
    TAccountOpenOrdersAccount,
    TAccountTriggerAuthority,
    TAccountFillsLog,
    TAccountMarket,
    TAccountOrderbookProgram,
    TAccountSystemProgram
  >);
}

export type ParsedPlaceTriggerOrderInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Fee payer */
    signer: TAccountMetas[0];
    /** Trigger order PDA */
    triggerOrder: TAccountMetas[1];
    /** Open orders account PDA */
    openOrdersAccount: TAccountMetas[2];
    /** Trigger authority PDA */
    triggerAuthority: TAccountMetas[3];
    /** FillsLog PDA */
    fillsLog: TAccountMetas[4];
    /** Market state PDA */
    market: TAccountMetas[5];
    /** Orderbook program */
    orderbookProgram: TAccountMetas[6];
    /** System program */
    systemProgram: TAccountMetas[7];
  };
  data: PlaceTriggerOrderInstructionData;
};

export function parsePlaceTriggerOrderInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPlaceTriggerOrderInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 8,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      triggerOrder: getNextAccount(),
      openOrdersAccount: getNextAccount(),
      triggerAuthority: getNextAccount(),
      fillsLog: getNextAccount(),
      market: getNextAccount(),
      orderbookProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPlaceTriggerOrderInstructionDataDecoder().decode(instruction.data),
  };
}
