/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { TRIGGER_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const PLACE_TRIGGER_ORDER_DISCRIMINATOR = 0;

export function getPlaceTriggerOrderDiscriminatorBytes() {
  return getU8Encoder().encode(PLACE_TRIGGER_ORDER_DISCRIMINATOR);
}

export type PlaceTriggerOrderInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountTriggerOrder extends string | AccountMeta<string> = string,
  TAccountOpenOrdersAccount extends string | AccountMeta<string> = string,
  TAccountTriggerAuthority extends string | AccountMeta<string> = string,
  TAccountFillsLog extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountOrderbookProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTriggerOrder extends string
        ? WritableAccount<TAccountTriggerOrder>
        : TAccountTriggerOrder,
      TAccountOpenOrdersAccount extends string
        ? WritableAccount<TAccountOpenOrdersAccount>
        : TAccountOpenOrdersAccount,
      TAccountTriggerAuthority extends string
        ? ReadonlyAccount<TAccountTriggerAuthority>
        : TAccountTriggerAuthority,
      TAccountFillsLog extends string
        ? WritableAccount<TAccountFillsLog>
        : TAccountFillsLog,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountOrderbookProgram extends string
        ? ReadonlyAccount<TAccountOrderbookProgram>
        : TAccountOrderbookProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PlaceTriggerOrderInstructionData = {
  discriminator: number;
  clientOrderId: bigint;
  triggerPrice: bigint;
  sizeLots: bigint;
  expiry: bigint;
  marketIndex: number;
  triggerType: number;
  side: number;
  bump: number;
  bumpAuthority: number;
  bumpFillsLog: number;
  padding: ReadonlyUint8Array;
};

export type PlaceTriggerOrderInstructionDataArgs = {
  clientOrderId: number | bigint;
  triggerPrice: number | bigint;
  sizeLots: number | bigint;
  expiry: number | bigint;
  marketIndex: number;
  triggerType: number;
  side: number;
  bump: number;
  bumpAuthority: number;
  bumpFillsLog: number;
  padding: ReadonlyUint8Array;
};

export function getPlaceTriggerOrderInstructionDataEncoder(): FixedSizeEncoder<PlaceTriggerOrderInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["clientOrderId", getU64Encoder()],
      ["triggerPrice", getI64Encoder()],
      ["sizeLots", getI64Encoder()],
      ["expiry", getI64Encoder()],
      ["marketIndex", getU16Encoder()],
      ["triggerType", getU8Encoder()],
      ["side", getU8Encoder()],
      ["bump", getU8Encoder()],
      ["bumpAuthority", getU8Encoder()],
      ["bumpFillsLog", getU8Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 1)],
    ]),
    (value) => ({ ...value, discriminator: PLACE_TRIGGER_ORDER_DISCRIMINATOR }),
  );
}

export function getPlaceTriggerOrderInstructionDataDecoder(): FixedSizeDecoder<PlaceTriggerOrderInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["clientOrderId", getU64Decoder()],
    ["triggerPrice", getI64Decoder()],
    ["sizeLots", getI64Decoder()],
    ["expiry", getI64Decoder()],
    ["marketIndex", getU16Decoder()],
    ["triggerType", getU8Decoder()],
    ["side", getU8Decoder()],
    ["bump", getU8Decoder()],
    ["bumpAuthority", getU8Decoder()],
    ["bumpFillsLog", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 1)],
  ]);
}

export function getPlaceTriggerOrderInstructionDataCodec(): FixedSizeCodec<
  PlaceTriggerOrderInstructionDataArgs,
  PlaceTriggerOrderInstructionData
> {
  return combineCodec(
    getPlaceTriggerOrderInstructionDataEncoder(),
    getPlaceTriggerOrderInstructionDataDecoder(),
  );
}

export type PlaceTriggerOrderInput<
  TAccountSigner extends string = string,
  TAccountTriggerOrder extends string = string,
  TAccountOpenOrdersAccount extends string = string,
  TAccountTriggerAuthority extends string = string,
  TAccountFillsLog extends string = string,
  TAccountMarket extends string = string,
  TAccountOrderbookProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Fee payer */
  signer: TransactionSigner<TAccountSigner>;
  /** Trigger order PDA */
  triggerOrder: Address<TAccountTriggerOrder>;
  /** Open orders account PDA */
  openOrdersAccount: Address<TAccountOpenOrdersAccount>;
  /** Trigger authority PDA (taker for fills_log + OO delegate) */
  triggerAuthority: Address<TAccountTriggerAuthority>;
  /** FillsLog PDA (initialized via CPI) */
  fillsLog: Address<TAccountFillsLog>;
  /** Market state PDA */
  market: Address<TAccountMarket>;
  /** Orderbook program (CPI) */
  orderbookProgram: Address<TAccountOrderbookProgram>;
  /** System program */
  systemProgram?: Address<TAccountSystemProgram>;
  clientOrderId: PlaceTriggerOrderInstructionDataArgs["clientOrderId"];
  triggerPrice: PlaceTriggerOrderInstructionDataArgs["triggerPrice"];
  sizeLots: PlaceTriggerOrderInstructionDataArgs["sizeLots"];
  expiry: PlaceTriggerOrderInstructionDataArgs["expiry"];
  marketIndex: PlaceTriggerOrderInstructionDataArgs["marketIndex"];
  triggerType: PlaceTriggerOrderInstructionDataArgs["triggerType"];
  side: PlaceTriggerOrderInstructionDataArgs["side"];
  bump: PlaceTriggerOrderInstructionDataArgs["bump"];
  bumpAuthority: PlaceTriggerOrderInstructionDataArgs["bumpAuthority"];
  bumpFillsLog: PlaceTriggerOrderInstructionDataArgs["bumpFillsLog"];
  padding: PlaceTriggerOrderInstructionDataArgs["padding"];
};

export function getPlaceTriggerOrderInstruction<
  TAccountSigner extends string,
  TAccountTriggerOrder extends string,
  TAccountOpenOrdersAccount extends string,
  TAccountTriggerAuthority extends string,
  TAccountFillsLog extends string,
  TAccountMarket extends string,
  TAccountOrderbookProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
>(
  input: PlaceTriggerOrderInput<
    TAccountSigner,
    TAccountTriggerOrder,
    TAccountOpenOrdersAccount,
    TAccountTriggerAuthority,
    TAccountFillsLog,
    TAccountMarket,
    TAccountOrderbookProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): PlaceTriggerOrderInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountTriggerOrder,
  TAccountOpenOrdersAccount,
  TAccountTriggerAuthority,
  TAccountFillsLog,
  TAccountMarket,
  TAccountOrderbookProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRIGGER_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
    openOrdersAccount: {
      value: input.openOrdersAccount ?? null,
      isWritable: true,
    },
    triggerAuthority: {
      value: input.triggerAuthority ?? null,
      isWritable: false,
    },
    fillsLog: { value: input.fillsLog ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    orderbookProgram: {
      value: input.orderbookProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("triggerOrder", accounts.triggerOrder),
      getAccountMeta("openOrdersAccount", accounts.openOrdersAccount),
      getAccountMeta("triggerAuthority", accounts.triggerAuthority),
      getAccountMeta("fillsLog", accounts.fillsLog),
      getAccountMeta("market", accounts.market),
      getAccountMeta("orderbookProgram", accounts.orderbookProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getPlaceTriggerOrderInstructionDataEncoder().encode(
      args as PlaceTriggerOrderInstructionDataArgs,
    ),
    programAddress,
  } as PlaceTriggerOrderInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTriggerOrder,
    TAccountOpenOrdersAccount,
    TAccountTriggerAuthority,
    TAccountFillsLog,
    TAccountMarket,
    TAccountOrderbookProgram,
    TAccountSystemProgram
  >);
}

export type ParsedPlaceTriggerOrderInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Fee payer */
    signer: TAccountMetas[0];
    /** Trigger order PDA */
    triggerOrder: TAccountMetas[1];
    /** Open orders account PDA */
    openOrdersAccount: TAccountMetas[2];
    /** Trigger authority PDA (taker for fills_log + OO delegate) */
    triggerAuthority: TAccountMetas[3];
    /** FillsLog PDA (initialized via CPI) */
    fillsLog: TAccountMetas[4];
    /** Market state PDA */
    market: TAccountMetas[5];
    /** Orderbook program (CPI) */
    orderbookProgram: TAccountMetas[6];
    /** System program */
    systemProgram: TAccountMetas[7];
  };
  data: PlaceTriggerOrderInstructionData;
};

export function parsePlaceTriggerOrderInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPlaceTriggerOrderInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 8,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      triggerOrder: getNextAccount(),
      openOrdersAccount: getNextAccount(),
      triggerAuthority: getNextAccount(),
      fillsLog: getNextAccount(),
      market: getNextAccount(),
      orderbookProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPlaceTriggerOrderInstructionDataDecoder().decode(instruction.data),
  };
}
