/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { TRIGGER_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const RESUME_TRIGGER_DISCRIMINATOR = 6;

export function getResumeTriggerDiscriminatorBytes() {
  return getU8Encoder().encode(RESUME_TRIGGER_DISCRIMINATOR);
}

export type ResumeTriggerInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountTriggerOrder extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTriggerOrder extends string
        ? WritableAccount<TAccountTriggerOrder>
        : TAccountTriggerOrder,
      ...TRemainingAccounts,
    ]
  >;

export type ResumeTriggerInstructionData = { discriminator: number };

export type ResumeTriggerInstructionDataArgs = {};

export function getResumeTriggerInstructionDataEncoder(): FixedSizeEncoder<ResumeTriggerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", getU8Encoder()]]),
    (value) => ({ ...value, discriminator: RESUME_TRIGGER_DISCRIMINATOR }),
  );
}

export function getResumeTriggerInstructionDataDecoder(): FixedSizeDecoder<ResumeTriggerInstructionData> {
  return getStructDecoder([["discriminator", getU8Decoder()]]);
}

export function getResumeTriggerInstructionDataCodec(): FixedSizeCodec<
  ResumeTriggerInstructionDataArgs,
  ResumeTriggerInstructionData
> {
  return combineCodec(
    getResumeTriggerInstructionDataEncoder(),
    getResumeTriggerInstructionDataDecoder(),
  );
}

export type ResumeTriggerInput<
  TAccountSigner extends string = string,
  TAccountTriggerOrder extends string = string,
> = {
  /** Order owner */
  signer: TransactionSigner<TAccountSigner>;
  /** Trigger order PDA */
  triggerOrder: Address<TAccountTriggerOrder>;
};

export function getResumeTriggerInstruction<
  TAccountSigner extends string,
  TAccountTriggerOrder extends string,
  TProgramAddress extends Address = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
>(
  input: ResumeTriggerInput<TAccountSigner, TAccountTriggerOrder>,
  config?: { programAddress?: TProgramAddress },
): ResumeTriggerInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountTriggerOrder
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? TRIGGER_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    triggerOrder: { value: input.triggerOrder ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("triggerOrder", accounts.triggerOrder),
    ],
    data: getResumeTriggerInstructionDataEncoder().encode({}),
    programAddress,
  } as ResumeTriggerInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTriggerOrder
  >);
}

export type ParsedResumeTriggerInstruction<
  TProgram extends string = typeof TRIGGER_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Order owner */
    signer: TAccountMetas[0];
    /** Trigger order PDA */
    triggerOrder: TAccountMetas[1];
  };
  data: ResumeTriggerInstructionData;
};

export function parseResumeTriggerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedResumeTriggerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { signer: getNextAccount(), triggerOrder: getNextAccount() },
    data: getResumeTriggerInstructionDataDecoder().decode(instruction.data),
  };
}
