/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfPlanAndSendFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/program-client-core";
import {
  getCancelTriggerOrderInstruction,
  getEditTriggerInstruction,
  getExecuteTriggerInstruction,
  getPlaceTriggerOrderInstruction,
  getPruneExpiredTriggerInstruction,
  parseCancelTriggerOrderInstruction,
  parseEditTriggerInstruction,
  parseExecuteTriggerInstruction,
  parsePlaceTriggerOrderInstruction,
  parsePruneExpiredTriggerInstruction,
  type CancelTriggerOrderInput,
  type EditTriggerInput,
  type ExecuteTriggerInput,
  type ParsedCancelTriggerOrderInstruction,
  type ParsedEditTriggerInstruction,
  type ParsedExecuteTriggerInstruction,
  type ParsedPlaceTriggerOrderInstruction,
  type ParsedPruneExpiredTriggerInstruction,
  type PlaceTriggerOrderInput,
  type PruneExpiredTriggerInput,
} from "../instructions";

export const TRIGGER_PROGRAM_PROGRAM_ADDRESS =
  "FBux8UY7koXsvDp3GThjvtiMo4GagsDdkPDbU4VbQzV2" as Address<"FBux8UY7koXsvDp3GThjvtiMo4GagsDdkPDbU4VbQzV2">;

export enum TriggerProgramInstruction {
  PlaceTriggerOrder,
  EditTrigger,
  ExecuteTrigger,
  CancelTriggerOrder,
  PruneExpiredTrigger,
}

export function identifyTriggerProgramInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): TriggerProgramInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return TriggerProgramInstruction.PlaceTriggerOrder;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return TriggerProgramInstruction.EditTrigger;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return TriggerProgramInstruction.ExecuteTrigger;
  }
  if (containsBytes(data, getU8Encoder().encode(3), 0)) {
    return TriggerProgramInstruction.CancelTriggerOrder;
  }
  if (containsBytes(data, getU8Encoder().encode(4), 0)) {
    return TriggerProgramInstruction.PruneExpiredTrigger;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "triggerProgram" },
  );
}

export type ParsedTriggerProgramInstruction<
  TProgram extends string = "FBux8UY7koXsvDp3GThjvtiMo4GagsDdkPDbU4VbQzV2",
> =
  | ({
      instructionType: TriggerProgramInstruction.PlaceTriggerOrder;
    } & ParsedPlaceTriggerOrderInstruction<TProgram>)
  | ({
      instructionType: TriggerProgramInstruction.EditTrigger;
    } & ParsedEditTriggerInstruction<TProgram>)
  | ({
      instructionType: TriggerProgramInstruction.ExecuteTrigger;
    } & ParsedExecuteTriggerInstruction<TProgram>)
  | ({
      instructionType: TriggerProgramInstruction.CancelTriggerOrder;
    } & ParsedCancelTriggerOrderInstruction<TProgram>)
  | ({
      instructionType: TriggerProgramInstruction.PruneExpiredTrigger;
    } & ParsedPruneExpiredTriggerInstruction<TProgram>);

export function parseTriggerProgramInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedTriggerProgramInstruction<TProgram> {
  const instructionType = identifyTriggerProgramInstruction(instruction);
  switch (instructionType) {
    case TriggerProgramInstruction.PlaceTriggerOrder: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: TriggerProgramInstruction.PlaceTriggerOrder,
        ...parsePlaceTriggerOrderInstruction(instruction),
      };
    }
    case TriggerProgramInstruction.EditTrigger: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: TriggerProgramInstruction.EditTrigger,
        ...parseEditTriggerInstruction(instruction),
      };
    }
    case TriggerProgramInstruction.ExecuteTrigger: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: TriggerProgramInstruction.ExecuteTrigger,
        ...parseExecuteTriggerInstruction(instruction),
      };
    }
    case TriggerProgramInstruction.CancelTriggerOrder: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: TriggerProgramInstruction.CancelTriggerOrder,
        ...parseCancelTriggerOrderInstruction(instruction),
      };
    }
    case TriggerProgramInstruction.PruneExpiredTrigger: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: TriggerProgramInstruction.PruneExpiredTrigger,
        ...parsePruneExpiredTriggerInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "triggerProgram",
        },
      );
  }
}

export type TriggerProgramPlugin = {
  instructions: TriggerProgramPluginInstructions;
};

export type TriggerProgramPluginInstructions = {
  placeTriggerOrder: (
    input: PlaceTriggerOrderInput,
  ) => ReturnType<typeof getPlaceTriggerOrderInstruction> &
    SelfPlanAndSendFunctions;
  editTrigger: (
    input: EditTriggerInput,
  ) => ReturnType<typeof getEditTriggerInstruction> & SelfPlanAndSendFunctions;
  executeTrigger: (
    input: ExecuteTriggerInput,
  ) => ReturnType<typeof getExecuteTriggerInstruction> &
    SelfPlanAndSendFunctions;
  cancelTriggerOrder: (
    input: CancelTriggerOrderInput,
  ) => ReturnType<typeof getCancelTriggerOrderInstruction> &
    SelfPlanAndSendFunctions;
  pruneExpiredTrigger: (
    input: PruneExpiredTriggerInput,
  ) => ReturnType<typeof getPruneExpiredTriggerInstruction> &
    SelfPlanAndSendFunctions;
};

export type TriggerProgramPluginRequirements = ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function triggerProgramProgram() {
  return <T extends TriggerProgramPluginRequirements>(client: T) => {
    return {
      ...client,
      triggerProgram: <TriggerProgramPlugin>{
        instructions: {
          placeTriggerOrder: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getPlaceTriggerOrderInstruction(input),
            ),
          editTrigger: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getEditTriggerInstruction(input),
            ),
          executeTrigger: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getExecuteTriggerInstruction(input),
            ),
          cancelTriggerOrder: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCancelTriggerOrderInstruction(input),
            ),
          pruneExpiredTrigger: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getPruneExpiredTriggerInstruction(input),
            ),
        },
      },
    };
  };
}
