/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STRATEGY_PROGRAM_PROGRAM_ADDRESS } from "../programs";
import {
  getCreateStrategyParamsDecoder,
  getCreateStrategyParamsEncoder,
  type CreateStrategyParams,
  type CreateStrategyParamsArgs,
} from "../types";

export const CREATE_STRATEGY_DISCRIMINATOR = 0;

export function getCreateStrategyDiscriminatorBytes() {
  return getU8Encoder().encode(CREATE_STRATEGY_DISCRIMINATOR);
}

export type CreateStrategyInstruction<
  TProgram extends string = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountStrategyAccount extends string | AccountMeta<string> = string,
  TAccountStrategyAuthority extends string | AccountMeta<string> = string,
  TAccountOpenOrdersAccount extends string | AccountMeta<string> = string,
  TAccountFillsLog extends string | AccountMeta<string> = string,
  TAccountMarket extends string | AccountMeta<string> = string,
  TAccountOrderbookProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountStrategyAccount extends string
        ? WritableAccount<TAccountStrategyAccount>
        : TAccountStrategyAccount,
      TAccountStrategyAuthority extends string
        ? ReadonlyAccount<TAccountStrategyAuthority>
        : TAccountStrategyAuthority,
      TAccountOpenOrdersAccount extends string
        ? WritableAccount<TAccountOpenOrdersAccount>
        : TAccountOpenOrdersAccount,
      TAccountFillsLog extends string
        ? WritableAccount<TAccountFillsLog>
        : TAccountFillsLog,
      TAccountMarket extends string
        ? ReadonlyAccount<TAccountMarket>
        : TAccountMarket,
      TAccountOrderbookProgram extends string
        ? ReadonlyAccount<TAccountOrderbookProgram>
        : TAccountOrderbookProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateStrategyInstructionData = {
  discriminator: number;
  createStrategyParams: CreateStrategyParams;
};

export type CreateStrategyInstructionDataArgs = {
  createStrategyParams: CreateStrategyParamsArgs;
};

export function getCreateStrategyInstructionDataEncoder(): Encoder<CreateStrategyInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["createStrategyParams", getCreateStrategyParamsEncoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_STRATEGY_DISCRIMINATOR }),
  );
}

export function getCreateStrategyInstructionDataDecoder(): Decoder<CreateStrategyInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["createStrategyParams", getCreateStrategyParamsDecoder()],
  ]);
}

export function getCreateStrategyInstructionDataCodec(): Codec<
  CreateStrategyInstructionDataArgs,
  CreateStrategyInstructionData
> {
  return combineCodec(
    getCreateStrategyInstructionDataEncoder(),
    getCreateStrategyInstructionDataDecoder(),
  );
}

export type CreateStrategyInput<
  TAccountSigner extends string = string,
  TAccountStrategyAccount extends string = string,
  TAccountStrategyAuthority extends string = string,
  TAccountOpenOrdersAccount extends string = string,
  TAccountFillsLog extends string = string,
  TAccountMarket extends string = string,
  TAccountOrderbookProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  strategyAccount: Address<TAccountStrategyAccount>;
  strategyAuthority: Address<TAccountStrategyAuthority>;
  openOrdersAccount: Address<TAccountOpenOrdersAccount>;
  fillsLog: Address<TAccountFillsLog>;
  market: Address<TAccountMarket>;
  orderbookProgram: Address<TAccountOrderbookProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  createStrategyParams: CreateStrategyInstructionDataArgs["createStrategyParams"];
};

export function getCreateStrategyInstruction<
  TAccountSigner extends string,
  TAccountStrategyAccount extends string,
  TAccountStrategyAuthority extends string,
  TAccountOpenOrdersAccount extends string,
  TAccountFillsLog extends string,
  TAccountMarket extends string,
  TAccountOrderbookProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CreateStrategyInput<
    TAccountSigner,
    TAccountStrategyAccount,
    TAccountStrategyAuthority,
    TAccountOpenOrdersAccount,
    TAccountFillsLog,
    TAccountMarket,
    TAccountOrderbookProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateStrategyInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountStrategyAccount,
  TAccountStrategyAuthority,
  TAccountOpenOrdersAccount,
  TAccountFillsLog,
  TAccountMarket,
  TAccountOrderbookProgram,
  TAccountSystemProgram
> {
  const programAddress =
    config?.programAddress ?? STRATEGY_PROGRAM_PROGRAM_ADDRESS;

  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    strategyAccount: { value: input.strategyAccount ?? null, isWritable: true },
    strategyAuthority: {
      value: input.strategyAuthority ?? null,
      isWritable: false,
    },
    openOrdersAccount: {
      value: input.openOrdersAccount ?? null,
      isWritable: true,
    },
    fillsLog: { value: input.fillsLog ?? null, isWritable: true },
    market: { value: input.market ?? null, isWritable: false },
    orderbookProgram: {
      value: input.orderbookProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const args = { ...input };

  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("strategyAccount", accounts.strategyAccount),
      getAccountMeta("strategyAuthority", accounts.strategyAuthority),
      getAccountMeta("openOrdersAccount", accounts.openOrdersAccount),
      getAccountMeta("fillsLog", accounts.fillsLog),
      getAccountMeta("market", accounts.market),
      getAccountMeta("orderbookProgram", accounts.orderbookProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getCreateStrategyInstructionDataEncoder().encode(
      args as CreateStrategyInstructionDataArgs,
    ),
    programAddress,
  } as CreateStrategyInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountStrategyAccount,
    TAccountStrategyAuthority,
    TAccountOpenOrdersAccount,
    TAccountFillsLog,
    TAccountMarket,
    TAccountOrderbookProgram,
    TAccountSystemProgram
  >);
}

export type ParsedCreateStrategyInstruction<
  TProgram extends string = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    strategyAccount: TAccountMetas[1];
    strategyAuthority: TAccountMetas[2];
    openOrdersAccount: TAccountMetas[3];
    fillsLog: TAccountMetas[4];
    market: TAccountMetas[5];
    orderbookProgram: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
  };
  data: CreateStrategyInstructionData;
};

export function parseCreateStrategyInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateStrategyInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 8,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      strategyAccount: getNextAccount(),
      strategyAuthority: getNextAccount(),
      openOrdersAccount: getNextAccount(),
      fillsLog: getNextAccount(),
      market: getNextAccount(),
      orderbookProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateStrategyInstructionDataDecoder().decode(instruction.data),
  };
}
