/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STRATEGY_PROGRAM_PROGRAM_ADDRESS } from "../programs";
import {
  getEditStrategyParamsDecoder,
  getEditStrategyParamsEncoder,
  type EditStrategyParams,
  type EditStrategyParamsArgs,
} from "../types";

export const EDIT_STRATEGY_DISCRIMINATOR = 1;

export function getEditStrategyDiscriminatorBytes() {
  return getU8Encoder().encode(EDIT_STRATEGY_DISCRIMINATOR);
}

export type EditStrategyInstruction<
  TProgram extends string = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountStrategyAccount extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountStrategyAccount extends string
        ? WritableAccount<TAccountStrategyAccount>
        : TAccountStrategyAccount,
      ...TRemainingAccounts,
    ]
  >;

export type EditStrategyInstructionData = {
  discriminator: number;
  editStrategyParams: EditStrategyParams;
};

export type EditStrategyInstructionDataArgs = {
  editStrategyParams: EditStrategyParamsArgs;
};

export function getEditStrategyInstructionDataEncoder(): Encoder<EditStrategyInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["editStrategyParams", getEditStrategyParamsEncoder()],
    ]),
    (value) => ({ ...value, discriminator: EDIT_STRATEGY_DISCRIMINATOR }),
  );
}

export function getEditStrategyInstructionDataDecoder(): Decoder<EditStrategyInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["editStrategyParams", getEditStrategyParamsDecoder()],
  ]);
}

export function getEditStrategyInstructionDataCodec(): Codec<
  EditStrategyInstructionDataArgs,
  EditStrategyInstructionData
> {
  return combineCodec(
    getEditStrategyInstructionDataEncoder(),
    getEditStrategyInstructionDataDecoder(),
  );
}

export type EditStrategyInput<
  TAccountSigner extends string = string,
  TAccountStrategyAccount extends string = string,
> = {
  /** Fee payer */
  signer: TransactionSigner<TAccountSigner>;
  /** Strategy account PDA */
  strategyAccount: Address<TAccountStrategyAccount>;
  editStrategyParams: EditStrategyInstructionDataArgs["editStrategyParams"];
};

export function getEditStrategyInstruction<
  TAccountSigner extends string,
  TAccountStrategyAccount extends string,
  TProgramAddress extends Address = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
>(
  input: EditStrategyInput<TAccountSigner, TAccountStrategyAccount>,
  config?: { programAddress?: TProgramAddress },
): EditStrategyInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountStrategyAccount
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STRATEGY_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    strategyAccount: { value: input.strategyAccount ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("strategyAccount", accounts.strategyAccount),
    ],
    data: getEditStrategyInstructionDataEncoder().encode(
      args as EditStrategyInstructionDataArgs,
    ),
    programAddress,
  } as EditStrategyInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountStrategyAccount
  >);
}

export type ParsedEditStrategyInstruction<
  TProgram extends string = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Fee payer */
    signer: TAccountMetas[0];
    /** Strategy account PDA */
    strategyAccount: TAccountMetas[1];
  };
  data: EditStrategyInstructionData;
};

export function parseEditStrategyInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedEditStrategyInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { signer: getNextAccount(), strategyAccount: getNextAccount() },
    data: getEditStrategyInstructionDataDecoder().decode(instruction.data),
  };
}
