/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { STRATEGY_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const RESUME_STRATEGY_DISCRIMINATOR = 4;

export function getResumeStrategyDiscriminatorBytes() {
  return getU8Encoder().encode(RESUME_STRATEGY_DISCRIMINATOR);
}

export type ResumeStrategyInstruction<
  TProgram extends string = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountStrategyAccount extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountStrategyAccount extends string
        ? WritableAccount<TAccountStrategyAccount>
        : TAccountStrategyAccount,
      ...TRemainingAccounts,
    ]
  >;

export type ResumeStrategyInstructionData = { discriminator: number };

export type ResumeStrategyInstructionDataArgs = {};

export function getResumeStrategyInstructionDataEncoder(): FixedSizeEncoder<ResumeStrategyInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", getU8Encoder()]]),
    (value) => ({ ...value, discriminator: RESUME_STRATEGY_DISCRIMINATOR }),
  );
}

export function getResumeStrategyInstructionDataDecoder(): FixedSizeDecoder<ResumeStrategyInstructionData> {
  return getStructDecoder([["discriminator", getU8Decoder()]]);
}

export function getResumeStrategyInstructionDataCodec(): FixedSizeCodec<
  ResumeStrategyInstructionDataArgs,
  ResumeStrategyInstructionData
> {
  return combineCodec(
    getResumeStrategyInstructionDataEncoder(),
    getResumeStrategyInstructionDataDecoder(),
  );
}

export type ResumeStrategyInput<
  TAccountSigner extends string = string,
  TAccountStrategyAccount extends string = string,
> = {
  /** Fee payer */
  signer: TransactionSigner<TAccountSigner>;
  /** Strategy account PDA */
  strategyAccount: Address<TAccountStrategyAccount>;
};

export function getResumeStrategyInstruction<
  TAccountSigner extends string,
  TAccountStrategyAccount extends string,
  TProgramAddress extends Address = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
>(
  input: ResumeStrategyInput<TAccountSigner, TAccountStrategyAccount>,
  config?: { programAddress?: TProgramAddress },
): ResumeStrategyInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountStrategyAccount
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STRATEGY_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    strategyAccount: { value: input.strategyAccount ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("strategyAccount", accounts.strategyAccount),
    ],
    data: getResumeStrategyInstructionDataEncoder().encode({}),
    programAddress,
  } as ResumeStrategyInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountStrategyAccount
  >);
}

export type ParsedResumeStrategyInstruction<
  TProgram extends string = typeof STRATEGY_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Fee payer */
    signer: TAccountMetas[0];
    /** Strategy account PDA */
    strategyAccount: TAccountMetas[1];
  };
  data: ResumeStrategyInstructionData;
};

export function parseResumeStrategyInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedResumeStrategyInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { signer: getNextAccount(), strategyAccount: getNextAccount() },
    data: getResumeStrategyInstructionDataDecoder().decode(instruction.data),
  };
}
