/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type FillSettleParams = {
  takerBumpUser: number;
  takerBumpPosition: number;
  makerBumpUser: number;
  makerBumpPosition: number;
  makerBumpOo: number;
  padding: ReadonlyUint8Array;
};

export type FillSettleParamsArgs = FillSettleParams;

export function getFillSettleParamsEncoder(): FixedSizeEncoder<FillSettleParamsArgs> {
  return getStructEncoder([
    ["takerBumpUser", getU8Encoder()],
    ["takerBumpPosition", getU8Encoder()],
    ["makerBumpUser", getU8Encoder()],
    ["makerBumpPosition", getU8Encoder()],
    ["makerBumpOo", getU8Encoder()],
    ["padding", fixEncoderSize(getBytesEncoder(), 3)],
  ]);
}

export function getFillSettleParamsDecoder(): FixedSizeDecoder<FillSettleParams> {
  return getStructDecoder([
    ["takerBumpUser", getU8Decoder()],
    ["takerBumpPosition", getU8Decoder()],
    ["makerBumpUser", getU8Decoder()],
    ["makerBumpPosition", getU8Decoder()],
    ["makerBumpOo", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 3)],
  ]);
}

export function getFillSettleParamsCodec(): FixedSizeCodec<
  FillSettleParamsArgs,
  FillSettleParams
> {
  return combineCodec(
    getFillSettleParamsEncoder(),
    getFillSettleParamsDecoder(),
  );
}
