/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type OpenOrder = {
  id: ReadonlyUint8Array;
  clientId: bigint;
  lockedPrice: bigint;
  originalBaseLots: bigint;
  filledBaseLots: bigint;
  isFree: number;
  side: number;
  makerOut: number;
  padding: ReadonlyUint8Array;
};

export type OpenOrderArgs = {
  id: ReadonlyUint8Array;
  clientId: number | bigint;
  lockedPrice: number | bigint;
  originalBaseLots: number | bigint;
  filledBaseLots: number | bigint;
  isFree: number;
  side: number;
  makerOut: number;
  padding: ReadonlyUint8Array;
};

export function getOpenOrderEncoder(): FixedSizeEncoder<OpenOrderArgs> {
  return getStructEncoder([
    ["id", fixEncoderSize(getBytesEncoder(), 16)],
    ["clientId", getU64Encoder()],
    ["lockedPrice", getI64Encoder()],
    ["originalBaseLots", getI64Encoder()],
    ["filledBaseLots", getI64Encoder()],
    ["isFree", getU8Encoder()],
    ["side", getU8Encoder()],
    ["makerOut", getU8Encoder()],
    ["padding", fixEncoderSize(getBytesEncoder(), 5)],
  ]);
}

export function getOpenOrderDecoder(): FixedSizeDecoder<OpenOrder> {
  return getStructDecoder([
    ["id", fixDecoderSize(getBytesDecoder(), 16)],
    ["clientId", getU64Decoder()],
    ["lockedPrice", getI64Decoder()],
    ["originalBaseLots", getI64Decoder()],
    ["filledBaseLots", getI64Decoder()],
    ["isFree", getU8Decoder()],
    ["side", getU8Decoder()],
    ["makerOut", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 5)],
  ]);
}

export function getOpenOrderCodec(): FixedSizeCodec<OpenOrderArgs, OpenOrder> {
  return combineCodec(getOpenOrderEncoder(), getOpenOrderDecoder());
}
