/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type MarketState = {
  marketIndex: number;
  bump: number;
  paused: number;
  padding: ReadonlyUint8Array;
  name: ReadonlyUint8Array;
  admin: ReadonlyUint8Array;
  bids: ReadonlyUint8Array;
  asks: ReadonlyUint8Array;
  baseLotSize: bigint;
  quoteLotSize: bigint;
  seqNum: bigint;
  registrationTs: bigint;
  timeExpiry: bigint;
  reserved: ReadonlyUint8Array;
};

export type MarketStateArgs = {
  marketIndex: number;
  bump: number;
  paused: number;
  padding: ReadonlyUint8Array;
  name: ReadonlyUint8Array;
  admin: ReadonlyUint8Array;
  bids: ReadonlyUint8Array;
  asks: ReadonlyUint8Array;
  baseLotSize: number | bigint;
  quoteLotSize: number | bigint;
  seqNum: number | bigint;
  registrationTs: number | bigint;
  timeExpiry: number | bigint;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link MarketStateArgs} account data. */
export function getMarketStateEncoder(): FixedSizeEncoder<MarketStateArgs> {
  return getStructEncoder([
    ["marketIndex", getU16Encoder()],
    ["bump", getU8Encoder()],
    ["paused", getU8Encoder()],
    ["padding", fixEncoderSize(getBytesEncoder(), 4)],
    ["name", fixEncoderSize(getBytesEncoder(), 16)],
    ["admin", fixEncoderSize(getBytesEncoder(), 32)],
    ["bids", fixEncoderSize(getBytesEncoder(), 32)],
    ["asks", fixEncoderSize(getBytesEncoder(), 32)],
    ["baseLotSize", getI64Encoder()],
    ["quoteLotSize", getI64Encoder()],
    ["seqNum", getU64Encoder()],
    ["registrationTs", getI64Encoder()],
    ["timeExpiry", getI64Encoder()],
    ["reserved", fixEncoderSize(getBytesEncoder(), 64)],
  ]);
}

/** Gets the decoder for {@link MarketState} account data. */
export function getMarketStateDecoder(): FixedSizeDecoder<MarketState> {
  return getStructDecoder([
    ["marketIndex", getU16Decoder()],
    ["bump", getU8Decoder()],
    ["paused", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 4)],
    ["name", fixDecoderSize(getBytesDecoder(), 16)],
    ["admin", fixDecoderSize(getBytesDecoder(), 32)],
    ["bids", fixDecoderSize(getBytesDecoder(), 32)],
    ["asks", fixDecoderSize(getBytesDecoder(), 32)],
    ["baseLotSize", getI64Decoder()],
    ["quoteLotSize", getI64Decoder()],
    ["seqNum", getU64Decoder()],
    ["registrationTs", getI64Decoder()],
    ["timeExpiry", getI64Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 64)],
  ]);
}

/** Gets the codec for {@link MarketState} account data. */
export function getMarketStateCodec(): FixedSizeCodec<
  MarketStateArgs,
  MarketState
> {
  return combineCodec(getMarketStateEncoder(), getMarketStateDecoder());
}

export function decodeMarketState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<MarketState, TAddress>;
export function decodeMarketState<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<MarketState, TAddress>;
export function decodeMarketState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<MarketState, TAddress> | MaybeAccount<MarketState, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getMarketStateDecoder(),
  );
}

export async function fetchMarketState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<MarketState, TAddress>> {
  const maybeAccount = await fetchMaybeMarketState(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeMarketState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<MarketState, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeMarketState(maybeAccount);
}

export async function fetchAllMarketState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<MarketState>[]> {
  const maybeAccounts = await fetchAllMaybeMarketState(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeMarketState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<MarketState>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeMarketState(maybeAccount));
}

export function getMarketStateSize(): number {
  return 224;
}
