/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getOpenOrderDecoder,
  getOpenOrderEncoder,
  type OpenOrder,
  type OpenOrderArgs,
} from "../types";

export type OpenOrdersAccount = {
  owner: ReadonlyUint8Array;
  market: ReadonlyUint8Array;
  delegate: ReadonlyUint8Array;
  bump: number;
  padding: ReadonlyUint8Array;
  openOrders: Array<OpenOrder>;
  reserved: ReadonlyUint8Array;
};

export type OpenOrdersAccountArgs = {
  owner: ReadonlyUint8Array;
  market: ReadonlyUint8Array;
  delegate: ReadonlyUint8Array;
  bump: number;
  padding: ReadonlyUint8Array;
  openOrders: Array<OpenOrderArgs>;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link OpenOrdersAccountArgs} account data. */
export function getOpenOrdersAccountEncoder(): FixedSizeEncoder<OpenOrdersAccountArgs> {
  return getStructEncoder([
    ["owner", fixEncoderSize(getBytesEncoder(), 32)],
    ["market", fixEncoderSize(getBytesEncoder(), 32)],
    ["delegate", fixEncoderSize(getBytesEncoder(), 32)],
    ["bump", getU8Encoder()],
    ["padding", fixEncoderSize(getBytesEncoder(), 7)],
    ["openOrders", getArrayEncoder(getOpenOrderEncoder(), { size: 24 })],
    ["reserved", fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

/** Gets the decoder for {@link OpenOrdersAccount} account data. */
export function getOpenOrdersAccountDecoder(): FixedSizeDecoder<OpenOrdersAccount> {
  return getStructDecoder([
    ["owner", fixDecoderSize(getBytesDecoder(), 32)],
    ["market", fixDecoderSize(getBytesDecoder(), 32)],
    ["delegate", fixDecoderSize(getBytesDecoder(), 32)],
    ["bump", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 7)],
    ["openOrders", getArrayDecoder(getOpenOrderDecoder(), { size: 24 })],
    ["reserved", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

/** Gets the codec for {@link OpenOrdersAccount} account data. */
export function getOpenOrdersAccountCodec(): FixedSizeCodec<
  OpenOrdersAccountArgs,
  OpenOrdersAccount
> {
  return combineCodec(
    getOpenOrdersAccountEncoder(),
    getOpenOrdersAccountDecoder(),
  );
}

export function decodeOpenOrdersAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<OpenOrdersAccount, TAddress>;
export function decodeOpenOrdersAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<OpenOrdersAccount, TAddress>;
export function decodeOpenOrdersAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<OpenOrdersAccount, TAddress>
  | MaybeAccount<OpenOrdersAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getOpenOrdersAccountDecoder(),
  );
}

export async function fetchOpenOrdersAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<OpenOrdersAccount, TAddress>> {
  const maybeAccount = await fetchMaybeOpenOrdersAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeOpenOrdersAccount<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<OpenOrdersAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeOpenOrdersAccount(maybeAccount);
}

export async function fetchAllOpenOrdersAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<OpenOrdersAccount>[]> {
  const maybeAccounts = await fetchAllMaybeOpenOrdersAccount(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeOpenOrdersAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<OpenOrdersAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeOpenOrdersAccount(maybeAccount),
  );
}

export function getOpenOrdersAccountSize(): number {
  return 1096;
}
