/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type FundingState = {
  cumulativeIndex: bigint;
  lastFundingRate: bigint;
  lastUpdated: bigint;
  marketIndex: number;
  bump: number;
  padding: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

export type FundingStateArgs = {
  cumulativeIndex: number | bigint;
  lastFundingRate: number | bigint;
  lastUpdated: number | bigint;
  marketIndex: number;
  bump: number;
  padding: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link FundingStateArgs} account data. */
export function getFundingStateEncoder(): FixedSizeEncoder<FundingStateArgs> {
  return getStructEncoder([
    ["cumulativeIndex", getI64Encoder()],
    ["lastFundingRate", getI64Encoder()],
    ["lastUpdated", getI64Encoder()],
    ["marketIndex", getU16Encoder()],
    ["bump", getU8Encoder()],
    ["padding", fixEncoderSize(getBytesEncoder(), 5)],
    ["reserved", fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

/** Gets the decoder for {@link FundingState} account data. */
export function getFundingStateDecoder(): FixedSizeDecoder<FundingState> {
  return getStructDecoder([
    ["cumulativeIndex", getI64Decoder()],
    ["lastFundingRate", getI64Decoder()],
    ["lastUpdated", getI64Decoder()],
    ["marketIndex", getU16Decoder()],
    ["bump", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 5)],
    ["reserved", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

/** Gets the codec for {@link FundingState} account data. */
export function getFundingStateCodec(): FixedSizeCodec<
  FundingStateArgs,
  FundingState
> {
  return combineCodec(getFundingStateEncoder(), getFundingStateDecoder());
}

export function decodeFundingState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<FundingState, TAddress>;
export function decodeFundingState<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<FundingState, TAddress>;
export function decodeFundingState<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<FundingState, TAddress> | MaybeAccount<FundingState, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getFundingStateDecoder(),
  );
}

export async function fetchFundingState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<FundingState, TAddress>> {
  const maybeAccount = await fetchMaybeFundingState(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeFundingState<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<FundingState, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeFundingState(maybeAccount);
}

export async function fetchAllFundingState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<FundingState>[]> {
  const maybeAccounts = await fetchAllMaybeFundingState(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeFundingState(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<FundingState>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeFundingState(maybeAccount));
}

export function getFundingStateSize(): number {
  return 64;
}
