/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type InsuranceFund = {
  balance: bigint;
  totalCollected: bigint;
  totalPaidOut: bigint;
  bump: number;
  padding: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

export type InsuranceFundArgs = {
  balance: number | bigint;
  totalCollected: number | bigint;
  totalPaidOut: number | bigint;
  bump: number;
  padding: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link InsuranceFundArgs} account data. */
export function getInsuranceFundEncoder(): FixedSizeEncoder<InsuranceFundArgs> {
  return getStructEncoder([
    ["balance", getU64Encoder()],
    ["totalCollected", getU64Encoder()],
    ["totalPaidOut", getU64Encoder()],
    ["bump", getU8Encoder()],
    ["padding", fixEncoderSize(getBytesEncoder(), 7)],
    ["reserved", fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

/** Gets the decoder for {@link InsuranceFund} account data. */
export function getInsuranceFundDecoder(): FixedSizeDecoder<InsuranceFund> {
  return getStructDecoder([
    ["balance", getU64Decoder()],
    ["totalCollected", getU64Decoder()],
    ["totalPaidOut", getU64Decoder()],
    ["bump", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 7)],
    ["reserved", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

/** Gets the codec for {@link InsuranceFund} account data. */
export function getInsuranceFundCodec(): FixedSizeCodec<
  InsuranceFundArgs,
  InsuranceFund
> {
  return combineCodec(getInsuranceFundEncoder(), getInsuranceFundDecoder());
}

export function decodeInsuranceFund<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<InsuranceFund, TAddress>;
export function decodeInsuranceFund<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<InsuranceFund, TAddress>;
export function decodeInsuranceFund<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<InsuranceFund, TAddress> | MaybeAccount<InsuranceFund, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getInsuranceFundDecoder(),
  );
}

export async function fetchInsuranceFund<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<InsuranceFund, TAddress>> {
  const maybeAccount = await fetchMaybeInsuranceFund(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeInsuranceFund<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<InsuranceFund, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeInsuranceFund(maybeAccount);
}

export async function fetchAllInsuranceFund(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<InsuranceFund>[]> {
  const maybeAccounts = await fetchAllMaybeInsuranceFund(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeInsuranceFund(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<InsuranceFund>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeInsuranceFund(maybeAccount));
}

export function getInsuranceFundSize(): number {
  return 64;
}
