/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type UserAccount = {
  collateral: bigint;
  marginUsed: bigint;
  bump: number;
  positionCount: number;
  padding: ReadonlyUint8Array;
  owner: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

export type UserAccountArgs = {
  collateral: number | bigint;
  marginUsed: number | bigint;
  bump: number;
  positionCount: number;
  padding: ReadonlyUint8Array;
  owner: ReadonlyUint8Array;
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link UserAccountArgs} account data. */
export function getUserAccountEncoder(): FixedSizeEncoder<UserAccountArgs> {
  return getStructEncoder([
    ["collateral", getI64Encoder()],
    ["marginUsed", getI64Encoder()],
    ["bump", getU8Encoder()],
    ["positionCount", getU8Encoder()],
    ["padding", fixEncoderSize(getBytesEncoder(), 6)],
    ["owner", fixEncoderSize(getBytesEncoder(), 32)],
    ["reserved", fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

/** Gets the decoder for {@link UserAccount} account data. */
export function getUserAccountDecoder(): FixedSizeDecoder<UserAccount> {
  return getStructDecoder([
    ["collateral", getI64Decoder()],
    ["marginUsed", getI64Decoder()],
    ["bump", getU8Decoder()],
    ["positionCount", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 6)],
    ["owner", fixDecoderSize(getBytesDecoder(), 32)],
    ["reserved", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

/** Gets the codec for {@link UserAccount} account data. */
export function getUserAccountCodec(): FixedSizeCodec<
  UserAccountArgs,
  UserAccount
> {
  return combineCodec(getUserAccountEncoder(), getUserAccountDecoder());
}

export function decodeUserAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<UserAccount, TAddress>;
export function decodeUserAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<UserAccount, TAddress>;
export function decodeUserAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<UserAccount, TAddress> | MaybeAccount<UserAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getUserAccountDecoder(),
  );
}

export async function fetchUserAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<UserAccount, TAddress>> {
  const maybeAccount = await fetchMaybeUserAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeUserAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<UserAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeUserAccount(maybeAccount);
}

export async function fetchAllUserAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<UserAccount>[]> {
  const maybeAccounts = await fetchAllMaybeUserAccount(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeUserAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<UserAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeUserAccount(maybeAccount));
}

export function getUserAccountSize(): number {
  return 88;
}
