/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { RISK_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const COVER_BAD_DEBT_DISCRIMINATOR = 13;

export function getCoverBadDebtDiscriminatorBytes() {
  return getU8Encoder().encode(COVER_BAD_DEBT_DISCRIMINATOR);
}

export type CoverBadDebtInstruction<
  TProgram extends string = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
  TAccountCaller extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountMarketConfig extends string | AccountMeta<string> = string,
  TAccountFundingState extends string | AccountMeta<string> = string,
  TAccountInsuranceFund extends string | AccountMeta<string> = string,
  TAccountOracle extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCaller extends string
        ? ReadonlySignerAccount<TAccountCaller> &
            AccountSignerMeta<TAccountCaller>
        : TAccountCaller,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountMarketConfig extends string
        ? ReadonlyAccount<TAccountMarketConfig>
        : TAccountMarketConfig,
      TAccountFundingState extends string
        ? WritableAccount<TAccountFundingState>
        : TAccountFundingState,
      TAccountInsuranceFund extends string
        ? WritableAccount<TAccountInsuranceFund>
        : TAccountInsuranceFund,
      TAccountOracle extends string
        ? ReadonlyAccount<TAccountOracle>
        : TAccountOracle,
      ...TRemainingAccounts,
    ]
  >;

export type CoverBadDebtInstructionData = {
  discriminator: number;
  marketIndex: number;
  padding: ReadonlyUint8Array;
};

export type CoverBadDebtInstructionDataArgs = {
  marketIndex: number;
  padding: ReadonlyUint8Array;
};

export function getCoverBadDebtInstructionDataEncoder(): FixedSizeEncoder<CoverBadDebtInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["marketIndex", getU16Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 6)],
    ]),
    (value) => ({ ...value, discriminator: COVER_BAD_DEBT_DISCRIMINATOR }),
  );
}

export function getCoverBadDebtInstructionDataDecoder(): FixedSizeDecoder<CoverBadDebtInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["marketIndex", getU16Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 6)],
  ]);
}

export function getCoverBadDebtInstructionDataCodec(): FixedSizeCodec<
  CoverBadDebtInstructionDataArgs,
  CoverBadDebtInstructionData
> {
  return combineCodec(
    getCoverBadDebtInstructionDataEncoder(),
    getCoverBadDebtInstructionDataDecoder(),
  );
}

export type CoverBadDebtInput<
  TAccountCaller extends string = string,
  TAccountUserAccount extends string = string,
  TAccountPosition extends string = string,
  TAccountMarketConfig extends string = string,
  TAccountFundingState extends string = string,
  TAccountInsuranceFund extends string = string,
  TAccountOracle extends string = string,
> = {
  /** Anyone */
  caller: TransactionSigner<TAccountCaller>;
  /** Bad debt account */
  userAccount: Address<TAccountUserAccount>;
  /** Bad debt position */
  position: Address<TAccountPosition>;
  /** MarketConfig */
  marketConfig: Address<TAccountMarketConfig>;
  /** FundingState */
  fundingState: Address<TAccountFundingState>;
  /** InsuranceFund */
  insuranceFund: Address<TAccountInsuranceFund>;
  /** Switchboard oracle */
  oracle: Address<TAccountOracle>;
  marketIndex: CoverBadDebtInstructionDataArgs["marketIndex"];
  padding: CoverBadDebtInstructionDataArgs["padding"];
};

export function getCoverBadDebtInstruction<
  TAccountCaller extends string,
  TAccountUserAccount extends string,
  TAccountPosition extends string,
  TAccountMarketConfig extends string,
  TAccountFundingState extends string,
  TAccountInsuranceFund extends string,
  TAccountOracle extends string,
  TProgramAddress extends Address = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
>(
  input: CoverBadDebtInput<
    TAccountCaller,
    TAccountUserAccount,
    TAccountPosition,
    TAccountMarketConfig,
    TAccountFundingState,
    TAccountInsuranceFund,
    TAccountOracle
  >,
  config?: { programAddress?: TProgramAddress },
): CoverBadDebtInstruction<
  TProgramAddress,
  TAccountCaller,
  TAccountUserAccount,
  TAccountPosition,
  TAccountMarketConfig,
  TAccountFundingState,
  TAccountInsuranceFund,
  TAccountOracle
> {
  // Program address.
  const programAddress = config?.programAddress ?? RISK_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    caller: { value: input.caller ?? null, isWritable: false },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    marketConfig: { value: input.marketConfig ?? null, isWritable: false },
    fundingState: { value: input.fundingState ?? null, isWritable: true },
    insuranceFund: { value: input.insuranceFund ?? null, isWritable: true },
    oracle: { value: input.oracle ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("caller", accounts.caller),
      getAccountMeta("userAccount", accounts.userAccount),
      getAccountMeta("position", accounts.position),
      getAccountMeta("marketConfig", accounts.marketConfig),
      getAccountMeta("fundingState", accounts.fundingState),
      getAccountMeta("insuranceFund", accounts.insuranceFund),
      getAccountMeta("oracle", accounts.oracle),
    ],
    data: getCoverBadDebtInstructionDataEncoder().encode(
      args as CoverBadDebtInstructionDataArgs,
    ),
    programAddress,
  } as CoverBadDebtInstruction<
    TProgramAddress,
    TAccountCaller,
    TAccountUserAccount,
    TAccountPosition,
    TAccountMarketConfig,
    TAccountFundingState,
    TAccountInsuranceFund,
    TAccountOracle
  >);
}

export type ParsedCoverBadDebtInstruction<
  TProgram extends string = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Anyone */
    caller: TAccountMetas[0];
    /** Bad debt account */
    userAccount: TAccountMetas[1];
    /** Bad debt position */
    position: TAccountMetas[2];
    /** MarketConfig */
    marketConfig: TAccountMetas[3];
    /** FundingState */
    fundingState: TAccountMetas[4];
    /** InsuranceFund */
    insuranceFund: TAccountMetas[5];
    /** Switchboard oracle */
    oracle: TAccountMetas[6];
  };
  data: CoverBadDebtInstructionData;
};

export function parseCoverBadDebtInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCoverBadDebtInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 7,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      caller: getNextAccount(),
      userAccount: getNextAccount(),
      position: getNextAccount(),
      marketConfig: getNextAccount(),
      fundingState: getNextAccount(),
      insuranceFund: getNextAccount(),
      oracle: getNextAccount(),
    },
    data: getCoverBadDebtInstructionDataDecoder().decode(instruction.data),
  };
}
