/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { RISK_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const DEPOSIT_INSURANCE_DISCRIMINATOR = 14;

export function getDepositInsuranceDiscriminatorBytes() {
  return getU8Encoder().encode(DEPOSIT_INSURANCE_DISCRIMINATOR);
}

export type DepositInsuranceInstruction<
  TProgram extends string = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountInsuranceFund extends string | AccountMeta<string> = string,
  TAccountUserTokenAccount extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountInsuranceFund extends string
        ? WritableAccount<TAccountInsuranceFund>
        : TAccountInsuranceFund,
      TAccountUserTokenAccount extends string
        ? WritableAccount<TAccountUserTokenAccount>
        : TAccountUserTokenAccount,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DepositInsuranceInstructionData = {
  discriminator: number;
  amount: bigint;
  bumpVault: number;
  padding: ReadonlyUint8Array;
};

export type DepositInsuranceInstructionDataArgs = {
  amount: number | bigint;
  bumpVault: number;
  padding: ReadonlyUint8Array;
};

export function getDepositInsuranceInstructionDataEncoder(): FixedSizeEncoder<DepositInsuranceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["amount", getU64Encoder()],
      ["bumpVault", getU8Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 7)],
    ]),
    (value) => ({ ...value, discriminator: DEPOSIT_INSURANCE_DISCRIMINATOR }),
  );
}

export function getDepositInsuranceInstructionDataDecoder(): FixedSizeDecoder<DepositInsuranceInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["amount", getU64Decoder()],
    ["bumpVault", getU8Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 7)],
  ]);
}

export function getDepositInsuranceInstructionDataCodec(): FixedSizeCodec<
  DepositInsuranceInstructionDataArgs,
  DepositInsuranceInstructionData
> {
  return combineCodec(
    getDepositInsuranceInstructionDataEncoder(),
    getDepositInsuranceInstructionDataDecoder(),
  );
}

export type DepositInsuranceInput<
  TAccountSigner extends string = string,
  TAccountInsuranceFund extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountVault extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Depositor */
  signer: TransactionSigner<TAccountSigner>;
  /** InsuranceFund PDA */
  insuranceFund: Address<TAccountInsuranceFund>;
  /** User USDC ATA */
  userTokenAccount: Address<TAccountUserTokenAccount>;
  /** Program vault */
  vault: Address<TAccountVault>;
  /** Token program */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System program */
  systemProgram?: Address<TAccountSystemProgram>;
  amount: DepositInsuranceInstructionDataArgs["amount"];
  bumpVault: DepositInsuranceInstructionDataArgs["bumpVault"];
  padding: DepositInsuranceInstructionDataArgs["padding"];
};

export function getDepositInsuranceInstruction<
  TAccountSigner extends string,
  TAccountInsuranceFund extends string,
  TAccountUserTokenAccount extends string,
  TAccountVault extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
>(
  input: DepositInsuranceInput<
    TAccountSigner,
    TAccountInsuranceFund,
    TAccountUserTokenAccount,
    TAccountVault,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): DepositInsuranceInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountInsuranceFund,
  TAccountUserTokenAccount,
  TAccountVault,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? RISK_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    insuranceFund: { value: input.insuranceFund ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    vault: { value: input.vault ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("insuranceFund", accounts.insuranceFund),
      getAccountMeta("userTokenAccount", accounts.userTokenAccount),
      getAccountMeta("vault", accounts.vault),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getDepositInsuranceInstructionDataEncoder().encode(
      args as DepositInsuranceInstructionDataArgs,
    ),
    programAddress,
  } as DepositInsuranceInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountInsuranceFund,
    TAccountUserTokenAccount,
    TAccountVault,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedDepositInsuranceInstruction<
  TProgram extends string = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Depositor */
    signer: TAccountMetas[0];
    /** InsuranceFund PDA */
    insuranceFund: TAccountMetas[1];
    /** User USDC ATA */
    userTokenAccount: TAccountMetas[2];
    /** Program vault */
    vault: TAccountMetas[3];
    /** Token program */
    tokenProgram: TAccountMetas[4];
    /** System program */
    systemProgram: TAccountMetas[5];
  };
  data: DepositInsuranceInstructionData;
};

export function parseDepositInsuranceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDepositInsuranceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      insuranceFund: getNextAccount(),
      userTokenAccount: getNextAccount(),
      vault: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getDepositInsuranceInstructionDataDecoder().decode(instruction.data),
  };
}
