/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { RISK_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const REMOVE_MARGIN_DISCRIMINATOR = 8;

export function getRemoveMarginDiscriminatorBytes() {
  return getU8Encoder().encode(REMOVE_MARGIN_DISCRIMINATOR);
}

export type RemoveMarginInstruction<
  TProgram extends string = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountMarketConfig extends string | AccountMeta<string> = string,
  TAccountOracle extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountMarketConfig extends string
        ? ReadonlyAccount<TAccountMarketConfig>
        : TAccountMarketConfig,
      TAccountOracle extends string
        ? ReadonlyAccount<TAccountOracle>
        : TAccountOracle,
      ...TRemainingAccounts,
    ]
  >;

export type RemoveMarginInstructionData = {
  discriminator: number;
  amount: bigint;
  marketIndex: number;
  padding: ReadonlyUint8Array;
};

export type RemoveMarginInstructionDataArgs = {
  amount: number | bigint;
  marketIndex: number;
  padding: ReadonlyUint8Array;
};

export function getRemoveMarginInstructionDataEncoder(): FixedSizeEncoder<RemoveMarginInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", getU8Encoder()],
      ["amount", getI64Encoder()],
      ["marketIndex", getU16Encoder()],
      ["padding", fixEncoderSize(getBytesEncoder(), 6)],
    ]),
    (value) => ({ ...value, discriminator: REMOVE_MARGIN_DISCRIMINATOR }),
  );
}

export function getRemoveMarginInstructionDataDecoder(): FixedSizeDecoder<RemoveMarginInstructionData> {
  return getStructDecoder([
    ["discriminator", getU8Decoder()],
    ["amount", getI64Decoder()],
    ["marketIndex", getU16Decoder()],
    ["padding", fixDecoderSize(getBytesDecoder(), 6)],
  ]);
}

export function getRemoveMarginInstructionDataCodec(): FixedSizeCodec<
  RemoveMarginInstructionDataArgs,
  RemoveMarginInstructionData
> {
  return combineCodec(
    getRemoveMarginInstructionDataEncoder(),
    getRemoveMarginInstructionDataDecoder(),
  );
}

export type RemoveMarginInput<
  TAccountSigner extends string = string,
  TAccountUserAccount extends string = string,
  TAccountPosition extends string = string,
  TAccountMarketConfig extends string = string,
  TAccountOracle extends string = string,
> = {
  /** Trader */
  signer: TransactionSigner<TAccountSigner>;
  /** UserAccount PDA */
  userAccount: Address<TAccountUserAccount>;
  /** Position PDA */
  position: Address<TAccountPosition>;
  /** MarketConfig */
  marketConfig: Address<TAccountMarketConfig>;
  /** Switchboard oracle */
  oracle: Address<TAccountOracle>;
  amount: RemoveMarginInstructionDataArgs["amount"];
  marketIndex: RemoveMarginInstructionDataArgs["marketIndex"];
  padding: RemoveMarginInstructionDataArgs["padding"];
};

export function getRemoveMarginInstruction<
  TAccountSigner extends string,
  TAccountUserAccount extends string,
  TAccountPosition extends string,
  TAccountMarketConfig extends string,
  TAccountOracle extends string,
  TProgramAddress extends Address = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
>(
  input: RemoveMarginInput<
    TAccountSigner,
    TAccountUserAccount,
    TAccountPosition,
    TAccountMarketConfig,
    TAccountOracle
  >,
  config?: { programAddress?: TProgramAddress },
): RemoveMarginInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountUserAccount,
  TAccountPosition,
  TAccountMarketConfig,
  TAccountOracle
> {
  // Program address.
  const programAddress = config?.programAddress ?? RISK_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: false },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    marketConfig: { value: input.marketConfig ?? null, isWritable: false },
    oracle: { value: input.oracle ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("userAccount", accounts.userAccount),
      getAccountMeta("position", accounts.position),
      getAccountMeta("marketConfig", accounts.marketConfig),
      getAccountMeta("oracle", accounts.oracle),
    ],
    data: getRemoveMarginInstructionDataEncoder().encode(
      args as RemoveMarginInstructionDataArgs,
    ),
    programAddress,
  } as RemoveMarginInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountUserAccount,
    TAccountPosition,
    TAccountMarketConfig,
    TAccountOracle
  >);
}

export type ParsedRemoveMarginInstruction<
  TProgram extends string = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Trader */
    signer: TAccountMetas[0];
    /** UserAccount PDA */
    userAccount: TAccountMetas[1];
    /** Position PDA */
    position: TAccountMetas[2];
    /** MarketConfig */
    marketConfig: TAccountMetas[3];
    /** Switchboard oracle */
    oracle: TAccountMetas[4];
  };
  data: RemoveMarginInstructionData;
};

export function parseRemoveMarginInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRemoveMarginInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      userAccount: getNextAccount(),
      position: getNextAccount(),
      marketConfig: getNextAccount(),
      oracle: getNextAccount(),
    },
    data: getRemoveMarginInstructionDataDecoder().decode(instruction.data),
  };
}
