/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { RISK_PROGRAM_PROGRAM_ADDRESS } from "../programs";

export const SETTLE_FUNDING_DISCRIMINATOR = 10;

export function getSettleFundingDiscriminatorBytes() {
  return getU8Encoder().encode(SETTLE_FUNDING_DISCRIMINATOR);
}

export type SettleFundingInstruction<
  TProgram extends string = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountMarketConfig extends string | AccountMeta<string> = string,
  TAccountFundingState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? ReadonlySignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountUserAccount extends string
        ? WritableAccount<TAccountUserAccount>
        : TAccountUserAccount,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountMarketConfig extends string
        ? ReadonlyAccount<TAccountMarketConfig>
        : TAccountMarketConfig,
      TAccountFundingState extends string
        ? WritableAccount<TAccountFundingState>
        : TAccountFundingState,
      ...TRemainingAccounts,
    ]
  >;

export type SettleFundingInstructionData = { discriminator: number };

export type SettleFundingInstructionDataArgs = {};

export function getSettleFundingInstructionDataEncoder(): FixedSizeEncoder<SettleFundingInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", getU8Encoder()]]),
    (value) => ({ ...value, discriminator: SETTLE_FUNDING_DISCRIMINATOR }),
  );
}

export function getSettleFundingInstructionDataDecoder(): FixedSizeDecoder<SettleFundingInstructionData> {
  return getStructDecoder([["discriminator", getU8Decoder()]]);
}

export function getSettleFundingInstructionDataCodec(): FixedSizeCodec<
  SettleFundingInstructionDataArgs,
  SettleFundingInstructionData
> {
  return combineCodec(
    getSettleFundingInstructionDataEncoder(),
    getSettleFundingInstructionDataDecoder(),
  );
}

export type SettleFundingInput<
  TAccountSigner extends string = string,
  TAccountUserAccount extends string = string,
  TAccountPosition extends string = string,
  TAccountMarketConfig extends string = string,
  TAccountFundingState extends string = string,
> = {
  /** Trader */
  signer: TransactionSigner<TAccountSigner>;
  /** UserAccount PDA */
  userAccount: Address<TAccountUserAccount>;
  /** Position PDA */
  position: Address<TAccountPosition>;
  /** MarketConfig */
  marketConfig: Address<TAccountMarketConfig>;
  /** FundingState */
  fundingState: Address<TAccountFundingState>;
};

export function getSettleFundingInstruction<
  TAccountSigner extends string,
  TAccountUserAccount extends string,
  TAccountPosition extends string,
  TAccountMarketConfig extends string,
  TAccountFundingState extends string,
  TProgramAddress extends Address = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
>(
  input: SettleFundingInput<
    TAccountSigner,
    TAccountUserAccount,
    TAccountPosition,
    TAccountMarketConfig,
    TAccountFundingState
  >,
  config?: { programAddress?: TProgramAddress },
): SettleFundingInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountUserAccount,
  TAccountPosition,
  TAccountMarketConfig,
  TAccountFundingState
> {
  // Program address.
  const programAddress = config?.programAddress ?? RISK_PROGRAM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: false },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    marketConfig: { value: input.marketConfig ?? null, isWritable: false },
    fundingState: { value: input.fundingState ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("userAccount", accounts.userAccount),
      getAccountMeta("position", accounts.position),
      getAccountMeta("marketConfig", accounts.marketConfig),
      getAccountMeta("fundingState", accounts.fundingState),
    ],
    data: getSettleFundingInstructionDataEncoder().encode({}),
    programAddress,
  } as SettleFundingInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountUserAccount,
    TAccountPosition,
    TAccountMarketConfig,
    TAccountFundingState
  >);
}

export type ParsedSettleFundingInstruction<
  TProgram extends string = typeof RISK_PROGRAM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Trader */
    signer: TAccountMetas[0];
    /** UserAccount PDA */
    userAccount: TAccountMetas[1];
    /** Position PDA */
    position: TAccountMetas[2];
    /** MarketConfig */
    marketConfig: TAccountMetas[3];
    /** FundingState */
    fundingState: TAccountMetas[4];
  };
  data: SettleFundingInstructionData;
};

export function parseSettleFundingInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedSettleFundingInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      userAccount: getNextAccount(),
      position: getNextAccount(),
      marketConfig: getNextAccount(),
      fundingState: getNextAccount(),
    },
    data: getSettleFundingInstructionDataDecoder().decode(instruction.data),
  };
}
